<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateOWDDSTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('o_w_d_d_s', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('WddCode')->nullable();
            $table->integer('WtmCode')->nullable(); // Authorization Template
            $table->integer('OwnerID')->nullable(); // Production Code
            $table->integer('DocEntry')->nullable();
            $table->string('ObjType')->nullable();
            $table->date('DocDate')->nullable(); //Posting Date
            $table->integer('CurrStep')->nullable(); //Stage Code
            $table->string('Status', 1)->nullable(); //A=Generated by Authorizer, C=Canceled, N=Rejected, P=Generated, W=Pending, Y=Approved
            $table->string('Remarks', 254)->nullable();
            $table->integer('UserSign')->nullable();
            $table->string('IsDraft', 1)->nullable(); //N=No, Y=Yes
            $table->integer('MaxReqr')->nullable();
            $table->integer('MaxRejReqr')->nullable(); //Maximu Request
            $table->string('SrcDocEnt', 1)->nullable();
            $table->string('DraftType')->nullable(); //Draft Type
            $table->integer('DraftEntry')->nullable(); // Draft Internal Number
            $table->string('BFType', 1)->nullable(); //Business Flow Type     A=Create, U=Update
            $table->string('ProcessID', 1)->nullable();
            $table->string('ProcesStat', 1)->nullable(); // Approval Process Status     A=Generated by Authorizer, C=Canceled, N=Rejected, P=Generated, W=Pending, Y=Approved
            $table->string('StpUpdated', 1)->nullable(); //    Stages Updated
                      $table->integer('CompanyID')
                ->references('id')->on('companies')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('o_w_d_d_s');
    }
}
