<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateOITBSTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('o_i_t_b_s', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('ItmsGrpCod')->nullable();
            $table->string('ItmsGrpNam')->nullable();
            $table->string('Locked')->default('N');
            $table->string('DataSource')->default('N');
            $table->integer('UserSign')
                ->references('id')->on('users')->nullable();
            $table->integer('BalInvntAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('SaleCostAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('TransferAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('RevenuesAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('VarianceAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('DecreasAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('IncreasAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ReturnAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ExpensesAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('EURevenuAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('EUExpensAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('FrRevenuAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('FrExpensAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ExmptIncom')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('CycleCode')->nullable();
            $table->string('Alert')->nullable();
            ;
            $table->integer('PriceDifAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ExchangeAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('BalanceAcc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('PurchaseAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('PAReturnAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('PurchOfsAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ShpdGdsAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('VatRevAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('DecresGlAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('IncresGlAc')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->string('InvntSys')->nullable();
            $table->string('PlaningSys')->default('N');
            $table->string('PrcrmntMtd')->default('B');
            $table->integer('OrdrIntrvl')->nullable();
            $table->string('OrdrMulti')->nullable();
            ;
            $table->string('MinOrdrQty')->nullable();
            ;
            $table->integer('LeadTime')->nullable();
            $table->integer('StokRvlAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('StkOffsAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('WipAcct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('WipVarAcct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('CostRvlAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('CstOffsAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ExpClrAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ExpOfstAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('Object')->nullable();
            $table->integer('logInstanc')->nullable();
            $table->integer('userSign2')
                ->references('id')->on('users')->nullable();
            $table->integer('ARCMAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ARCMFrnAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ARCMEUAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ARCMExpAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('APCMAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('APCMFrnAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('APCMEUAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('RevRetAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('ItemClass')->nullable();
            $table->integer('OSvcCode')->nullable();
            $table->integer('ISvcCode')->nullable();
            $table->integer('ServiceGrp')->nullable();
            $table->integer('NCMCode')->nullable();
            $table->integer('MatType')->nullable();
            $table->integer('MatGrp')->nullable();
            $table->integer('ProductSrc')->nullable();
            $table->integer('NegStckAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('StkInTnAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('PurBalAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('WhICenAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('WhOCenAct')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('WipOffset')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('StockOffst')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('UgpEntry')
                ->references('id')->on('uo_m_groups')->nullable();
            $table->integer('IUoMEntry')->nullable();
            $table->integer('ToleranDay')->nullable();
            $table->integer('RuleCode')->nullable();
            $table->string('CompoWH')->default('B');
            $table->integer('FreeChrgSA')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('FreeChrgPU')
                ->references('id')->on('chart_of_accounts')->nullable();
            $table->integer('RawMtrl')->nullable();
            $table->string('ExtRef')->nullable(); //Name
            $table->integer('CompanyID')
                ->references('id')->on('companies')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('o_i_t_b_s');
    }
}
