<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateOOATSTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('o_o_a_t_s', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('BpCode', 15)
                ->references('id')->on('o_c_r_d_s')->nullable();
            $table->string('BpName', 150)->nullable();
            $table->string('CntctCode', 11)->default(0);
            $table->date('StartDate')->nullable();
            $table->date('EndDate')->nullable();
            $table->date('TermDate')->nullable();
            $table->string('Descript', 254)->nullable();
            $table->string('Type', 1)->default('G'); //G=General, S=Specific
            $table->string('Status', 1)->default('D'); //A=Approved, B=To Be Approved, C=Canceled, D=Draft, F=On Hold, P=To Be On Hold, T=Terminated, X=To Be Terminated
            $table->string('Owner', 11)->nullable();
            $table->string('Renewal', 1)->default('N'); //N=No, Y=Yes
            $table->string('UseDiscnt', 1)->default('Y'); //N=No, Y=Yes
            $table->string('RemindVal', 1)->nullable();
            $table->string('RemindUnit', 1)->default('D'); //D=Day(s), M=Month(s), W=Week(s)
            $table->string('Remarks', 200)->nullable();
            $table->string('AtchEntry', 11)->nullable();
            $table->string('LogInstanc', 11)->nullable();
            $table->integer('UserSign')->nullable();
            $table->integer('UserSign2')->nullable();
            $table->string('UpdtDate')->nullable();
            $table->string('CreateDate')->nullable();
            $table->string('Cancelled', 1)->default('N'); //N=No, Y=Yes
            $table->string('DataSource', 1)->default('N'); //A=Auto Summary, D=Restore Wizard, I=Interface, M=Import, N=Unknown, O=DI API, P=Partner Implementation, T=Year of Transfer, U=Upgrade
            $table->string('Transfered', 1)->default('N'); //N=No, Y=Yes
            $table->string('RemindFlg', 1)->default('N'); //N=No, Y=Yes
            $table->string('Fulfilled', 1)->default('N'); //N=Not Fulfilled, Y=Fulfilled
            $table->string('Attachment', 16)->nullable();
            $table->float('SettleProb', 19, 6)->default(0);
            $table->string('UpdtTime', 1)->nullable();
            $table->string('Method', 1)->default('I'); //I=Items Method, M=Monetary Method
            $table->string('GroupNum', 6)->default(0);
            $table->string('ListNum', 6)
                ->references('id')->on('currencies')->nullable();
            $table->date('SignDate')->nullable();
            $table->string('AmendedTo', 11)->nullable();
            $table->string('Series', 11)->nullable();
            $table->string('Number', 11)->nullable();
            $table->string('ObjType', 20)->default('1250000025');
            $table->string('Handwrtten', 1)->default('N');
            $table->string('PIndicator', 11)->nullable();
            $table->string('BpType', 1)->default('C'); //C=Customer, S=Vendor
            $table->string('Instance', 6)->default(0);
            $table->string('PayMethod', 1)->nullable();
            $table->string('NumAtCard', 100)->nullable();
            $table->string('BPCurr')
                ->references('id')->on('currencies')->nullable();
            $table->float('FixedRate', 19, 6)->nullable();
            $table->string('TrnspCode', 1)->nullable();
            $table->string('Project', 1)->nullable();
            $table->string('PriceMode', 1)->default('N'); //G=Gross, N=Net
            $table->string('WddStatus', 1)->default('-'); //-=Without, A=Generated by Authorizer, C=Canceled, N=Rejected, P=Generated, W=Pending, Y=Approved
            $table->string('FromStat', 1)->default('D'); //D=Draft, F=On Hold
            $table->string('DPPStatus', 1)->default('N'); //D=Erased, N=None
            $table->string('SAPPassprt', 16)->nullable();

            //User Defined Fields
            $table->date('U_LeaseStartDate')->nullable();
            $table->float('U_Months', 19, 2)->nullable();
            $table->date('U_LeaseEndDate')->nullable();
            $table->float('U_ExtensionMonths', 19, 2)->nullable();
            $table->integer('CompanyID')
                ->references('id')->on('companies')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('o_o_a_t_s');
    }
}
