<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateOACPSTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('o_a_c_p_s', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('AbsEntry')->nullable();
            $table->integer('PeriodCat')->nullable();
            $table->date('FinancYear')->nullable();
            $table->integer('Year')->nullable();
            $table->string('PeriodName')->nullable();
            $table->integer('SubType')->nullable();
            $table->integer('PeriodNum')->nullable();
            $table->date('F_RefDate')->nullable();
            $table->date('T_RefDate')->nullable();
            $table->date('F_DueDate')->nullable();
            $table->date('T_DueDate')->nullable();
            $table->date('F_TaxDate')->nullable();
            $table->date('T_TaxDate')->nullable();
            $table->integer('LogInstanc')->nullable();
            $table->integer('UpdateDate')->nullable();
            $table->integer('UserSign')->nullable();
            $table->integer('LinkAct_1')->nullable(); // Account Receivable
            $table->integer('LinkAct_2')->nullable();
            $table->integer('LinkAct_3')->nullable();
            $table->integer('LinkAct_4')->nullable();
            $table->integer('LinkAct_5')->nullable();
            $table->integer('LinkAct_6')->nullable();
            $table->integer('ComissAct')->nullable();
            $table->integer('LinkAct_8')->nullable();
            $table->integer('LinkAct_9')->nullable();
            $table->integer('LinkAct_10')->nullable();
            $table->integer('LinkAct_11')->nullable();
            $table->integer('LinkAct_12')->nullable();
            $table->integer('LinkAct_13')->nullable();
            $table->integer('LinkAct_14')->nullable();
            $table->integer('LinkAct_15')->nullable();
            $table->integer('LinkAct_16')->nullable();
            $table->integer('LinkAct_17')->nullable();
            $table->integer('LinkAct_18')->nullable();
            $table->integer('DfltIncom')->nullable();
            $table->integer('ExmptIncom')->nullable();
            $table->integer('DfltExpn')->nullable();
            $table->integer('ForgnIncm')->nullable();
            $table->integer('ECIncome')->nullable();
            $table->integer('ForgnExpn')->nullable();
            $table->integer('DfltRateDi')->nullable();
            $table->integer('DecresGlAc')->nullable();
            $table->integer('LinkAct_27')->nullable();
            $table->integer('DftStockOB')->nullable();
            $table->integer('LinkAct_19')->nullable();
            $table->integer('LinkAct_20')->nullable();
            $table->integer('LinkAct_21')->nullable();
            $table->integer('LinkAct_22')->nullable();
            $table->integer('LinkAct_23')->nullable();
            $table->integer('LinkAct_24')->nullable();
            $table->integer('LinkAct_25')->nullable();
            $table->integer('LinkAct_26')->nullable();
            $table->integer('IncresGlAc')->nullable();
            $table->integer('RturnngAct')->nullable();
            $table->integer('COGM_Act')->nullable();
            $table->integer('AlocCstAct')->nullable();
            $table->integer('VariancAct')->nullable();
            $table->integer('PricDifAct')->nullable();
            $table->integer('CDownPymnt')->nullable();
            $table->integer('VDownPymnt')->nullable();
            $table->integer('CBoERcvble')->nullable();
            $table->integer('CBoEOnClct')->nullable();
            $table->integer('CBoEPresnt')->nullable();
            $table->integer('CBoEDiscnt')->nullable();
            $table->integer('CUnpaidBoE')->nullable();
            $table->integer('VBoEPayble')->nullable();
            $table->integer('VAsstBoEPy')->nullable();
            $table->integer('COpenDebts')->nullable();
            $table->integer('VOpenDebts')->nullable();
            $table->integer('PurchseAct')->nullable();
            $table->integer('PaReturnAc')->nullable();
            $table->integer('PaOffsetAc')->nullable();
            $table->integer('LinkAct_28')->nullable();
            $table->integer('ExDiffAct')->nullable();
            $table->integer('BalanceAct')->nullable();
            $table->integer('BnkChgAct')->nullable();
            $table->integer('LinkAct_29')->nullable();
            $table->integer('LinkAct_30')->nullable();
            $table->integer('IncmAcct')->nullable();
            $table->integer('ExpnAcct')->nullable();
            $table->integer('VatRevAct')->nullable();
            $table->integer('ExpClrAct')->nullable();
            $table->integer('ExpOfstAct')->nullable();
            $table->integer('CostRevAct')->nullable();
            $table->integer('RepomoAct')->nullable();
            $table->integer('WipVarAcct')->nullable();
            $table->integer('SaleVatOff')->nullable();
            $table->integer('PurcVatOff')->nullable();
            $table->integer('DpmSalAct')->nullable();
            $table->integer('DpmPurAct')->nullable();
            $table->integer('ExpVarAct')->nullable();
            $table->integer('CostOffAct')->nullable();
            $table->integer('ECExepnses')->nullable();
            $table->integer('StockAct')->nullable();
            $table->integer('DflInPrcss')->nullable();
            $table->integer('DfltInCstm')->nullable();
            $table->integer('DfltProfit')->nullable();
            $table->integer('DfltLoss')->nullable();
            $table->integer('VAssets')->nullable();
            $table->integer('StockRvAct')->nullable();
            $table->integer('StkRvOfAct')->nullable();
            $table->integer('WipAcct')->nullable();
            $table->integer('DfltCard')->nullable();
            $table->integer('ShpdGdsAct')->nullable();
            $table->integer('GlRvOffAct')->nullable();
            $table->integer('OverpayAP')->nullable();
            $table->integer('UndrpayAP')->nullable();
            $table->integer('OverpayAR')->nullable();
            $table->integer('UndrpayAR')->nullable();
            $table->integer('ARCMAct')->nullable();
            $table->integer('ARCMExpAct')->nullable();
            $table->integer('ARCMFrnAct')->nullable();
            $table->integer('ARCMEUAct')->nullable();
            $table->integer('APCMAct')->nullable();
            $table->integer('APCMFrnAct')->nullable();
            $table->integer('APCMEUAct')->nullable();
            $table->integer('NegStckAct')->nullable();
            $table->integer('StkInTnAct')->nullable();
            $table->integer('GLGainXdif')->nullable();
            $table->integer('GLLossXdif')->nullable();
            $table->integer('AmountDiff')->nullable();
            $table->integer('SlfInvIncm')->nullable();
            $table->integer('SlfInvExpn')->nullable();
            $table->integer('OnHoldAct')->nullable();
            $table->integer('PlaAct')->nullable();
            $table->integer('ICClrAct')->nullable();
            $table->integer('OCClrAct')->nullable();
            $table->integer('PurBalAct')->nullable();
            $table->integer('WhICenAct')->nullable();
            $table->integer('WhOCenAct')->nullable();
            $table->integer('SalDpmInt')->nullable();
            $table->integer('PurDpmInt')->nullable();
            $table->integer('ExrateOnDt')->nullable();
            $table->integer('UserSign2')->nullable();
            $table->integer('EURecvAct')->nullable();
            $table->integer('EUPayAct')->nullable();
            $table->integer('WipOffset')->nullable();
            $table->integer('StockOffst')->nullable();
            $table->integer('DunIntrst')->nullable();
            $table->integer('DunFee')->nullable();
            $table->integer('SnapShotId')->nullable();
            $table->integer('TDSInterst')->nullable();
            $table->integer('TDSCharges')->nullable();
            $table->integer('SrvTaxClr')->nullable();
            $table->integer('ARConDiffG')->nullable();
            $table->integer('ARConDiffL')->nullable();
            $table->integer('APConDiffG')->nullable();
            $table->integer('APConDiffL')->nullable();
            $table->integer('GLConDiffG')->nullable();
            $table->integer('GLConDiffL')->nullable();
            $table->integer('FreeChrgSA')->nullable();
            $table->integer('FreeChrgPU')->nullable();
            $table->integer('TDSFee')->nullable();
            $table->integer('ResRevenue')->nullable();
            $table->integer('ResExpense')->nullable();
            $table->integer('ResSalesCr')->nullable();
            $table->integer('ResPurchCr')->nullable();
            $table->integer('ResNotInv')->nullable();
            $table->integer('ResStdExp1')->nullable();
            $table->integer('ResStdExp2')->nullable();
            $table->integer('ResStdExp3')->nullable();
            $table->integer('ResStdExp4')->nullable();
            $table->integer('ResStdExp5')->nullable();
            $table->integer('ResStdExp6')->nullable();
            $table->integer('ResStdExp7')->nullable();
            $table->integer('ResStdExp8')->nullable();
            $table->integer('ResStdExp9')->nullable();
            $table->integer('ResStdEx10')->nullable();
            $table->integer('ResWipAct')->nullable();
            $table->integer('ResScrapAc')->nullable();
            $table->integer('WipOffPlAc')->nullable();
            $table->integer('ResOffPlAc')->nullable();
            $table->integer('ERDInARAct')->nullable();
            $table->integer('ERDInAPAct')->nullable();
            $table->integer('CSDInARAct')->nullable();
            $table->integer('CSDInAPAct')->nullable();
            $table->integer('GSTInAct')->nullable();
            $table->integer('GSTInterst')->nullable();
            $table->integer('GSTCharges')->nullable();
            $table->integer('GSTFee')->nullable();

            $table->integer('Radius')->default(70)->comment("For Mobile App");
            $table->integer('PostDoubleEntry')->default(0);
            $table->integer('CompanyID')
                ->references('id')->on('companies')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('o_a_c_p_s');
    }
}
